### PR TITLE
dismiss popup when touch event end

### PR DESCRIPTION
**Pull request by wencharmwang**
the popup can't dismiss somehow because of the alpha animation.
use visibility instead of the value of alpha

### CODE REVIEW

**Comment by timusus** [comment]
I don't understand what you mean by 'popup can't dismiss somehow..'. It's dismissing just fine on my test devices. What API level are we talking about? Do you have steps to reproduce.

The mVisible flag is used to determine whether the animation should run, based on whether the current visibility matches the desired visibility.

The isVisible() method is a little different - it's used for determining whether the popup is showing, and returns false if our section name text is null, which means the popup doesn't get drawn unnecessarily - which is the desired effect.

Closed: Not enough information.

**Comment by wencharmwang** [comment]
Sorry to reply so late. I haven't looked into the code carefully because I got so busy these days. 
But I can reproduce the issue and could send you the video if you want.BTW, I changed to another implementation for the fast scroll bar because the scroll bar jumps between items in this branch which's really annoying.I expect you could make this branch perfect for all kinds of devices. :+1:

**Comment by timusus** [comment]
Thanks for the response. Yes, a video would be great. I'm not really sure what this 'fix' is addressing! Otherwise, you could just try and describe the problem.

I'm not sure what you mean about the scroll bar 'jumping'. Have you tried the latest build?

**Comment by wencharmwang** [comment]
I can’t reproduce the “scroll bar jumping between items” now without the test device.
This is the video which show the popup issue.

Wencharm Wang

**Comment by wencharmwang** [comment]
@timusus have received the video in the email? I'm not sure if it works.
please tell me if you got the video.

**Comment by timusus** [comment]
You should upload the video and link it here for anyone to see. No, I haven't received a video via e-mail.

**Comment by wencharmwang** [comment]
[screenrecord.mp4.zip](https://github.com/timusus/RecyclerView-FastScroll/files/111171/screenrecord.mp4.zip)
I haven't found any good way to upload .mp4 file.
please download the compress one.

**Comment by timusus** [comment]
Your video is describing a much more complex problem than a simple visibility issue - it looks like you have many different types of items within your list. I don't think the library is able to correctly map the section positions to the RecyclerView position - because you have a header, and some intermediate items which don't contribute to the section count (or something like that). A RecyclerView/Adapter of this complexity is not currently supported by this library, you might have to make some changes yourself and see if you can get it working.

**Comment by wencharmwang** [comment]
@timusus thanks dude. I already implement it in another way.

**Pull request closed without merging**
